# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            May1601
tagline:          'A pluggable industrial honeypot'
description:      'A pluggable industrial control system honeypot, with automated build and deployment. Written in Go.'
<<<<<<< HEAD
url:              http://may1601.sd.ece.iastate.edu
baseurl:          /
=======
url:              http://May1601.sd.ece.iastate.edu
baseurl:          http://May1601.sd.ece.iastate.edu/www
>>>>>>> master

github:
  repo:           https://github.com/Senior-Design-May1601
